config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#landing'

  devise_for :users,
             path: '',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

  resources :properties, only: %i[index show], to: 'pages#react'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :properties, only: %i[index show create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user, inverse_of: :properties

  validates :name, presence: true
  validates :city, presence: true
  validates :street_name, presence: true
  validates :building_number, presence: true
  validates :zip_code, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties, inverse_of: :users
end

app/controllers/api/v1/properties_controller.rb
class Api::V1::PropertiesController < ActionController::Base
  before_action :set_property, only: %i[show destroy]

  def index
    properties = Property.all
    render json: properties
  end

  def show
    render json: @property, include: { user: { only: %i[first_name last_name] } }
  end

  def create
    property = Property.create(property_params)
    render json: property
  end

  def destroy
    @property.destroy
    head :no_content
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:propery).permit(
      :name,
      :description,
      :city,
      :street_name,
      :building_number,
      :zip_code
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  prepend_view_path Rails.root.join('frontend')

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :landing

  def react; end

  def landing
    @properties = Property.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def should_render_react
    routes = Rails.configuration.rails_routes
    current_path = request.env['PATH_INFO'].gsub(/\//, '')
    current_path = 'root' if current_path.empty?
    !routes.include? current_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Rails.application.class.parent_name %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag "application" if should_render_react %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
<p>Landing (rails)</p>

<% if user_signed_in? %>
  <%= link_to 'Log Out', destroy_user_session_path %>
<% else %>
  <%= link_to 'Log In', new_user_session_path %>
  <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

<%= link_to 'Properties', properties_path %>

<ul>
  <% @properties.each do |property| %>
    <li><%= property.name %></li>
  <% end %>
</ul>

app/views/pages/react.html.erb
<div id='react'></div>